wallpaper {
  monitor = eDP-1
  path = ~/.config/backgrounds/nice-blue-background.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-1
  path = ~/.config/backgrounds/nice-blue-background.png
  fit_mode = cover
}
